{{- /* Code generated by gen-app-helpers. DO NOT EDIT */}}




{{- define "infra-traefik.common.labels" -}}
helm.sh/chart: {{ include "infra-traefik.chart" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}