nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "executionTime"
  type: "avg"
cases:
- name: "functionExecutionTime_1"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(5)
- name: "functionExecutionTime_2"
  root: "./bench2"
  file: "bench.ts"
  trigger: seq(5)
- name: "functionExecutionTime_3"
  root: "./bench3"
  file: "bench.ts"
  trigger: seq(5)
- name: "functionExecutionTime_4"
  root: "./bench4"
  file: "bench.ts"
  trigger: seq(5)