nest:
  host: 172.27.152.238:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "executionTime"
  type: "avg"
cases:
- name: "function execution time - 1"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(10)
- name: "function execution time - 2"
  root: "./bench2"
  file: "bench.ts"
  trigger: seq(10)
- name: "function execution time - 3"
  root: "./bench3"
  file: "bench.ts"
  trigger: seq(10)
- name: "function execution time - 4"
  root: "./bench4"
  file: "bench.ts"
  trigger: seq(10)