nest:
  host: 172.27.152.238:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "communicationTime"
  type: "avg"
cases:
- name: "function communication time"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(10)