nest:
  host: 172.27.152.238:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "communicationTime"
  type: "avg"
cases:
- name: "function communication time - 1"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(10)
- name: "function communication time - 2"
  root: "./bench1"
  file: "bench.ts"
  trigger: sud(50)
- name: "function communication time - 3"
  root: "./bench1"
  file: "bench.ts"
  trigger: sud(200)