nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "communicationTime"
  type: "avg"
cases:
- name: "functionCommunicationTime_1"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(5)
- name: "functionCommunicationTime_2"
  root: "./bench1"
  file: "bench.ts"
  trigger: sud(10)
- name: "functionCommunicationTime_3"
  root: "./bench1"
  file: "bench.ts"
  trigger: sud(50)