nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "configModificationTime"
  type: "avg"
cases:
- name: "configuration modification time"
  root: "./bench2"
  file: "bench.ts"
  trigger: seq(5)