/*
 * generated by Xtext 2.28.0-SNAPSHOT
 */
package cn.njuics.faasit.dsl.formatting2;

import cn.njuics.faasit.dsl.faasIt.Block;
import cn.njuics.faasit.dsl.faasIt.Model;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

public class FaasItFormatter extends AbstractJavaFormatter {

	protected void format(Model model, IFormattableDocument doc) {
	}
}
