/*
 * generated by Xtext 2.30.0
 */
package cn.njuics.faasit.dsl.formatting2;

import cn.njuics.faasit.dsl.faasIt.Greeting;
import cn.njuics.faasit.dsl.faasIt.Model;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

public class MyDslFormatter extends AbstractJavaFormatter {

	protected void format(Model model, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Greeting greeting : model.getGreetings()) {
			doc.format(greeting);
		}
	}
	
}
