/*
 * generated by Xtext unknown
 */
package cn.njuics.faasit.dsl.generator;

import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class FaasItGenerator extends AbstractGenerator {

	public void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
        var fileName = URI.decode(resource.getURI().trimFileExtension().lastSegment());
        fsa.generateFile(fileName+"Greeter.java", """
        public class «fileName»Greeter {
            
            public static void main(String[] args) {
                «FOR g : resource.allContents.filter(Greeting).toIterable»
                    System.out.println("Hello «g.name» «IF g.from !== null» from «g.from.name»«ENDIF»!");
                «ENDFOR»
            }
            
        }
        """);
	}
}
