/*
 * generated by Xtext 2.30.0
 */
package cn.njuics.faasit.dsl.tests;

import cn.njuics.faasit.dsl.faasIt.Model;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.resource.Resource.Diagnostic;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(FaasItInjectorProvider.class)
public class FaasItParsingTest {
	@Inject
	private ParseHelper<Model> parseHelper;
	
	@Test
	public void loadModel() throws Exception {
		Model result = parseHelper.parse("Hello Xtext!");
		Assert.assertNotNull(result);
		List<Diagnostic> errors = result.eResource().getErrors();
		Assert.assertTrue("Unexpected errors: " + IterableExtensions.join(errors, ", "), errors.isEmpty());
	}
}
