/*
 * generated by Xtext 2.23.0
 */
package cn.njuics.faasit.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FaasItStandaloneSetup extends FaasItStandaloneSetupGenerated {

	public static void doSetup() {
		new FaasItStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
