nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "executionTime"
  type: "avg"
- name: "cpuUsage"
  type: "avg"
- name: "logicalCores"
  type: "avg"
- name: "memoryUsage"
  type: "avg"
- name: "peakMemoryUsage"
  type: "max"
cases:
- name: "stability"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(1)