nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "funcUpdateTime"
  type: "avg"
cases:
- name: "functionUpdateTime"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq(5)