/*
 * generated by Xtext 2.23.0
 */
package cn.njuics.faasit.dsl.validation;

import cn.njuics.faasit.dsl.faasIt.FaasItPackage;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class FaasItValidator extends AbstractFaasItValidator {
	
	public static final String INVALID_NAME = "invalidName";
}
