nest:
  host: localhost:8080
  database: benchmark
metrics:
- name: "times"
  type: "sum"
- name: "coldTime"
  type: "avg"
- name: "coldComTime"
  type: "avg"
- name: "warmComTime"
  type: "avg"
cases:
- name: "cold startup time"
  root: "./bench1"
  file: "bench.ts"
  trigger: seq