/*
 * generated by Xtext 2.30.0
 */
package cn.njuics.faasit.dsl.ide;

import cn.njuics.faasit.dsl.FaasItRuntimeModule;
import cn.njuics.faasit.dsl.FaasItStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FaasItIdeSetup extends FaasItStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FaasItRuntimeModule(), new FaasItIdeModule()));
	}
	
}
